name: CI-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Проверка обновления приложения
        run: |
          if git show HEAD^:package.json > /dev/null 2>&1; then
            PREV_VERSION=$(git show HEAD^:package.json | grep '"version"' | head -1 | awk -F '"' '{print $4}')
            CUR_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F '"' '{print $4}')
            if [ "$PREV_VERSION" = "$CUR_VERSION" ]; then
              echo "Версия не изменена! Обновите версию в package.json."
              exit 1
            fi
          else
            echo "Нет предыдущего коммита, проверка версии пропущена."
          fi

      - name: Установка зависимостей
        run: npm install
      - name: Проверка линтинга
        run: npm run lint
      - name: Проверка prettier
        run: npm run format
