services:
  frontend-shop.co:
    build:
      context: .
      dockerfile: Dockerfile
      # Порт заменить на нужный при деплое проекта
    ports:
      - '3011:80' # Проброс порта 3011 на порт 80 контейнера
    volumes:
      - ./dist:/usr/share/nginx/html:rw 
    stdin_open: true 
    logging: 
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
